## Load Dataset

In [31]:
import pandas as pd

In [32]:
df_train_q = pd.read_csv('./dataset/train_questions.csv')
df_train_q

,question_id,question,course,year,candidate_answers,answer_id
0,79062,"For categorical target set, where the distribu...",Machine Learning Zoomcamp,2021,"156400,754877,105368,643810,912439",156400
1,468946,Is there anything that we are not allowed to u...,Machine Learning Zoomcamp,2021,"641330,634887,912439,425941,642829",634887
2,968800,I have been catching up and have been doing ho...,Data Engineering Zoomcamp,2022,"954016,167856,75919,36798,838013",954016
3,688404,Could you please explain what code we should l...,Data Engineering Zoomcamp,2022,"198661,629898,686577,3699,141765",3699
4,63921,Is it just me or does the model have really ba...,Machine Learning Zoomcamp,2021,"754877,604487,912439,858915,425941",858915
...,...,...,...,...,...,...
392,241788,Can the model with the ROC AUC score of around...,Machine Learning Zoomcamp,2021,"274012,831391,912439,596854,214199",831391
393,595103,When I click tab in the parentheses of the iPy...,Machine Learning Zoomcamp,2021,"325935,651754,478055,214199,912439",651754
394,450348,Can you please explain the use cases of Splunk...,Data Engineering Zoomcamp,2022,"432981,908368,296080,131069,733226",733226
395,864660,Why did you use model2bin in the last question...,Machine Learning Zoomcamp,2021,"40420,422297,32377,169051,623076",422297
396,205640,Would you mind clarifying evaluation on test a...,Machine Learning Zoomcamp,2021,"604487,754877,558889,214199,596854",558889

In [33]:
df_train_ans = pd.read_csv('./dataset/train_answers.csv')
df_train_ans

,answer_id,answer,course,year,attachments_files
0,156400,Alexey\nShould we use something non-standard t...,Machine Learning Zoomcamp,2021,NaN
1,634887,"No, I don't think there is anything you cannot...",Machine Learning Zoomcamp,2021,NaN
2,954016,"Alexey\nYes, you will be. You can submit the p...",Data Engineering Zoomcamp,2022,NaN
3,3699,Alexey\nI think the question refers to the hom...,Data Engineering Zoomcamp,2022,NaN
4,858915,"Dmitry\nIt's fine, because this is the showcas...",Machine Learning Zoomcamp,2021,NaN
...,...,...,...,...,...
392,831391,"Yes, it can. It's really dataset dependent. Fo...",Machine Learning Zoomcamp,2021,NaN
393,651754,"Let's say I do “import numpy as np” and then, ...",Machine Learning Zoomcamp,2021,NaN
394,733226,Alexey\nSplunk – I don’t know. It's not a data...,Data Engineering Zoomcamp,2022,NaN
395,422297,"Yes, it was not mentioned. But what was mentio...",Machine Learning Zoomcamp,2021,NaN
396,558889,Alexey\nI guess the question is why we need to...,Machine Learning Zoomcamp,2021,NaN

In [34]:
df_test_q = pd.read_csv('./dataset/test_questions.csv')
df_test_q

,question_id,question,course,year,candidate_answers
0,707,How much of an effort would it be to use AWS i...,Data Engineering Zoomcamp,2023,"336232,337669,258304,47681,767296"
1,534450,Can you talk about linear regression and regul...,Machine Learning Zoomcamp,2022,"231208,282072,86769,573165,138373"
2,996163,Can you please explain the Python Black setup ...,Data Engineering Zoomcamp,2023,"571892,816559,47681,337669,336232"
3,860215,How many portfolio projects apart from the cou...,Machine Learning Zoomcamp,2022,"643931,988549,918931,235894,608866"
4,980124,Can you talk more about the final project? Wha...,Data Engineering Zoomcamp,2023,"384381,337669,258304,47681,747722"
...,...,...,...,...,...
511,385696,How can we contribute to the course?,Data Engineering Zoomcamp,2023,"258304,630862,856125,47681,366701"
512,178777,How should I organize my data lake – by depart...,Data Engineering Zoomcamp,2023,"757091,337669,557268,521840,336232"
513,134025,What Java aspects will be covered in the cours...,Data Engineering Zoomcamp,2023,"125560,323555,770524,47681,366701"
514,881774,The retries of tasks can be notified? Or do we...,Data Engineering Zoomcamp,2023,"585024,922526,647021,337669,844757"
515,678022,Can you explain regularization better? I did n...,Machine Learning Zoomcamp,2022,"917151,364660,539366,296131,944884"

In [35]:
df_test_ans = pd.read_csv('./dataset/train_questions.csv')
df_test_ans

,question_id,question,course,year,candidate_answers,answer_id
0,79062,"For categorical target set, where the distribu...",Machine Learning Zoomcamp,2021,"156400,754877,105368,643810,912439",156400
1,468946,Is there anything that we are not allowed to u...,Machine Learning Zoomcamp,2021,"641330,634887,912439,425941,642829",634887
2,968800,I have been catching up and have been doing ho...,Data Engineering Zoomcamp,2022,"954016,167856,75919,36798,838013",954016
3,688404,Could you please explain what code we should l...,Data Engineering Zoomcamp,2022,"198661,629898,686577,3699,141765",3699
4,63921,Is it just me or does the model have really ba...,Machine Learning Zoomcamp,2021,"754877,604487,912439,858915,425941",858915
...,...,...,...,...,...,...
392,241788,Can the model with the ROC AUC score of around...,Machine Learning Zoomcamp,2021,"274012,831391,912439,596854,214199",831391
393,595103,When I click tab in the parentheses of the iPy...,Machine Learning Zoomcamp,2021,"325935,651754,478055,214199,912439",651754
394,450348,Can you please explain the use cases of Splunk...,Data Engineering Zoomcamp,2022,"432981,908368,296080,131069,733226",733226
395,864660,Why did you use model2bin in the last question...,Machine Learning Zoomcamp,2021,"40420,422297,32377,169051,623076",422297
396,205640,Would you mind clarifying evaluation on test a...,Machine Learning Zoomcamp,2021,"604487,754877,558889,214199,596854",558889

## EDA

#### Sample of question with the answer candidate

In [36]:
df_train_q.iloc[1]['question']

'Is there anything that we are not allowed to use? For example, if you want to use hyper-parameter tuning, are we allowed to use GridSearchCV, RandomizedSearchCV?'

In [37]:
candidate_answers_ids = df_train_q.at[1,'candidate_answers'].split(",")
candidate_answers_ids

['641330', '634887', '912439', '425941', '642829']

In [38]:
df_train_ans[df_train_ans['answer_id'].isin(candidate_answers_ids)]

,answer_id,answer,course,year,attachments_files
1,634887,"No, I don't think there is anything you cannot...",Machine Learning Zoomcamp,2021,NaN
39,641330,"44. Two people submitted twice. So actually, i...",Machine Learning Zoomcamp,2021,NaN
96,642829,Alexey\nOne thing that maybe I wasn't clear en...,Machine Learning Zoomcamp,2021,NaN
251,912439,"Yes. In addition to that, ideally, it will be ...",Machine Learning Zoomcamp,2021,NaN
300,425941,Dmitry\nUsually I use the NumPy function. \nAl...,Machine Learning Zoomcamp,2021,NaN

#### Example of correct candidate answer

In [65]:
df_train_ans[df_train_ans['answer_id'] == 634887]['answer'].iloc[0]

"No, I don't think there is anything you cannot use. I just want to ask you to document it, if there is something you use that is not a part of the course. For somebody who will be reviewing your project, it will be new information. So just give them some context and explain, “I used GridSearchCV because this is easier and this is what you can do.” Then you describe it, and you give your peers a chance to learn from what you’re doing. This way, they will not be lost and will be able to grade your homework. If you do that, you can use whatever you want.\xa0\nFrom the materials in the course, like if you use logistic regression, or rich regression, or XGBoost, or random forest, then you don't need to really go into details when documenting because I would expect that people understand that without much explanation. Maybe it's also a good idea if somebody, let's say, wants to use not XGBoost, but LightGBM, or CatBoost, which are different implementations of gradient boosting – you're free to use them in your project as well. You can use FastAPI instead of Flask, for example. You can use Poetry instead of Pipenv. You can use Conda instead of Pipenv. You're basically free to explore to use what you want and play with different tools, just be sure to document that."

#### Example of incorrect candidate answer

In [66]:
df_train_ans[df_train_ans['answer_id'] == 641330]['answer'].iloc[0]

"44. Two people submitted twice. So actually, it's 42 unique submissions. I hope with the extension, many more people will be able to work on the project. I know that maybe many of you were putting things off until the last day and then something didn't work. It happens to me all the time as well. But if you now focus on putting things in Flask and then putting them in Docker, you should be good. If you’re training a model right now, stop it and go to the deployment part. Then you'll be good."